name: MLOps with CML

on: [push, pull_request]

jobs:

  train-and-report:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: DVC and Python setup
        uses: iterative/setup-dvc@v1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # --- CONFIGURE DVC REMOTE ---
      - name: Configure DVC Remote
        env:
          DAGSHUB_API_KEY: ${{ secrets.DAGSHUB_API_KEY }}
        run: |
          dvc remote modify origin --local access_key_id $DAGSHUB_API_KEY
          dvc remote modify origin --local secret_access_key $DAGSHUB_API_KEY

      - name: DVC Pull
        continue-on-error: true
        run: dvc pull -r origin

      # --- INSTALL DEPENDENCIES ---
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- TRAIN MODEL ---
      - name: Run DVC pipeline (train)
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_API_KEY }}
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        run: dvc repro


  # -----------------------------------------------------------  
  #                    DEPLOY TO GKE  
  # -----------------------------------------------------------
  deploy-to-gke:
    needs: train-and-report
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: DVC and Python setup
        uses: iterative/setup-dvc@v1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # --- AUTHENTICATE GOOGLE CLOUD ---
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud CLI and kubectl
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          install_components: 'gke-gcloud-auth-plugin'

      - name: Configure DVC Remote
        env:
          DAGSHUB_API_KEY: ${{ secrets.DAGSHUB_API_KEY }}
        run: |
          dvc remote modify origin --local access_key_id $DAGSHUB_API_KEY
          dvc remote modify origin --local secret_access_key $DAGSHUB_API_KEY

      - name: DVC Pull Model
        run: dvc pull -r origin

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ vars.GKE_CLUSTER }} \
          --zone ${{ vars.GKE_ZONE }} \
          --project ${{ vars.GCP_PROJECT_ID }}

      # --- INSTALL DEPENDENCIES ---
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- CONFIGURE DOCKER ---
      # - name: Configure Docker to use GCR
      #   run: gcloud auth configure-docker

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      # ---- BUILD AND PUSH API IMAGE ----
      - name: Build and Push API
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/mlops-api/mlops-api:latest .
          docker push us-central1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/mlops-api/mlops-api:latest

      # ---- BUILD AND PUSH WEB IMAGE ----
      - name: Build and Push WEB
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}mlops-web/mlops-web:latest -f Dockerfile.web .
          docker push us-central1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}mlops-web/mlops-web:latest

      # ---- DEPLOY TO GKE ----
      - name: Deploy to GKE
        run: |
          kubectl apply -f api-deployment.yaml
          kubectl apply -f api-service.yaml
          kubectl apply -f web-deployment.yaml
          kubectl apply -f web-service.yaml
